### ISSUE TITLE
MQTT retain option

### ISSUE THREAD

**Issue by digitalcraig** [haruny/adt-pulse-mqtt#18]
@haruny why did you specify retain: false option for MQTT publish of zone updates? The alarm status is pushed with retain: true and that's persistent. I am troubleshooting why my motion detector and camera motion zones don't ever seem to push to MQTT (I'm guess it's happening between syncs?) and noticed that I mostly only see devStatOk or devStatusOkCamera get logged to console, rarely even even see devStatOpen. I know door state changes are making it to Home Assistant reliably, but I don't see them in the log or in my MQTT sniffer.

Any ideas?

My zones:

adt/zone/BACK DOOR/state
adt/zone/Carbon Monoxide Detec/state
adt/zone/FRONT DOOR/state
adt/zone/GARAGE DOOR/state
adt/zone/HALL MOTION/state
adt/zone/Hallway SmokeDetector/state
adt/zone/MASTER GLASS/state
adt/zone/Camera/state

I'm trying to make sure I can determine the correct payloads for Home Assistant. Doors are working great, the rest not quite working yet.

**Comment by haruny** [comment]
I think retain wouldn’t matter since in every restart it does a full refresh of devices. However if you have multiple apps using the MQTT topics you may need the retain the states as the updates maybe running at different  times. On the other hand, you need the commands as retain=false. Otherwise you would start echoing the same command multiple times. 

Regarding the motion detectors...
Try to confirm in your pulse site device list. My motion detectors show as “notable events only”.
 ADT pulse only triggers them on notable events such as device temper or events that break the alarm. That’s why any motion trigger normally wouldn’t be reflected immediately when the alarm is not set. 
Do you see your motion detectors trigger on pulse website when the alarm is in disarm status? If yours are different, there might be a bug. Please share your pulse page output when the motion detectors are triggered. It should be an easy fix.

**Comment by digitalcraig** [comment]
No longer an issue.
