### ISSUE TITLE
Incorrect MQTT topics for Sensor Updates

### ISSUE THREAD

**Issue by egobyte** [haruny/adt-pulse-mqtt#43]
Noticed in the latest update that whenever a sensor is "opened" it correctly sends "devStatOpen/devStatTamper" to the correct MQTT topic, however when that sensor is closed, it sends "devStatOk" to the alphabetically first sensor. In my case, when I open my garage door, it correctly sends open to "adt/zone/Garage Door/state", but when I close it, it sends OK to "adt/zone/Back Door/state". I also tested with my front door sensor, same result. Is this also related to the cheerio bug?

**Comment by gary-albano** [comment]
I would not **think** so. I haven not seen that issue thus far.

**Comment by digitalcraig** [comment]
It is possible. Cheerio has been publishing 1.0.0 release candidates to npm so it's hard to say what kind of state that library is in when/if your local installation rebuilds the add-on container. I did commit an update which updates the library dependencies to a known good working version rather than "latest". Uninstalling and reinstalling the add-on (save your config) should force it to pull down the new dependencies and rebuild the add-on container. However, it may make more sense for me to just bump the version number so everyone gets the update.

The better option for now may be to use [this add-on repository](https://github.com/digitalcraig/hassio) which instead points to a Docker Hub image rather than use a locally built container. That image has been stable for 8 months and eliminates these issues caused by locally built add-on containers.

Just as side note, I'm working to eliminate the confusion between multiple repositories and forks by creating a definitive repo under a new Github and Docker organization/team. They are created, I just need to get everything moved over.

**Comment by egobyte** [comment]
I tried rebuilding and had the same issue. 

However the Docker Hub image works perfectly so I guess issue resolved.

**Comment by digitalcraig** [comment]
Glad to hear it.
